#!/usr/bin/env bash
# Unit tests for `ng nexus-identity` (cmd_nexus_identity in monitor/ng).
#
# Run: bash monitor/watcher/test-ng-nexus-identity.sh
# Expected: ALL TESTS PASSED on stdout, exit 0.
#
# Strategy: a fake nexus (setup_fake_nexus) supplies the ng binary +
# config stub; NEXUS_ROOT is pointed at the fake root so the
# working-directory headline and watcher pidfile/log paths derive from
# it. A PATH-shadowed `gh` captures the PATCH on the --upsert-overview
# path. The fake root is intentionally NOT a git checkout, so the
# implementation-clone row must degrade gracefully.
#
# Coverage:
#   --dry-run renders both delimiters, the working-directory headline,
#     every field label, and reflects NEXUS_ROOT + the config repo.
#   --dry-run is idempotent (two runs identical) — the anti-drift point.
#   implementation-clone row falls back when root isn't a git checkout.
#   --upsert-overview issues a PATCH whose body carries the identity
#     block between the delimiters (bot identity / REST PATCH).
#   the upsert awk replaces an existing block in place (no duplicate).

set -uo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/_test_helpers.sh"

WORK=$(mktemp -d -t nexus-ng-identity-XXXXXX)
trap 'rm -rf "$WORK"' EXIT

setup_fake_nexus "$WORK/nexus" --allow-default --repo 'your-org/example-nexus'
NG="$FAKE_NEXUS/monitor/ng"

STUB_DIR="$WORK/bin"
CAPTURE="$WORK/gh-calls.txt"
BODY_CAPTURE="$WORK/gh-body.txt"

# `gh` stub: a single overview issue (#1) with a canned body; PATCH
# echoes an html_url and the piped JSON body is captured for inspection.
# MOCK_BODY_FILE overrides the GET body (used to seed an existing block).
make_gh_stub "$STUB_DIR/gh" "$CAPTURE" --with-body-capture "$BODY_CAPTURE" <<'CASES'
    */issues\?labels=nexus:overview*|*/issues?labels=nexus:overview*)
        printf '[{"number":1,"title":"Nexus"}]'
        ;;
    */issues/[0-9]*)
        if [[ "$method" == "PATCH" ]]; then
            printf '%s' '{"html_url":"https://mock.example/issues/1"}'
            return 0 2>/dev/null || exit 0
        fi
        if [[ -n "${MOCK_BODY_FILE:-}" && -f "${MOCK_BODY_FILE:-}" ]]; then
            jq -Rs '{body: .}' < "$MOCK_BODY_FILE"
        else
            printf '%s' '{"body":"## Nexus overview\n\nbody prose\n"}'
        fi
        ;;
    *)
        printf '%s' '{}'
        ;;
CASES

NEUTRAL_CWD="$WORK/neutral"
mkdir -p "$NEUTRAL_CWD"

run_ng() {
    local _out_var="$1" _err_var="$2" _rc_var="$3"; shift 3
    local _stdout _stderr _rc _out_tmp _err_tmp
    _out_tmp=$(mktemp); _err_tmp=$(mktemp)
    : > "$CAPTURE"; : > "$BODY_CAPTURE"
    ( cd "$NEUTRAL_CWD" && run_hermetic \
        NEXUS_ROOT="$FAKE_NEXUS" \
        NEXUS_STATE_DIR="$WORK/state" \
        PATH="$STUB_DIR:$PATH" \
        MOCK_BODY_FILE="${MOCK_BODY_FILE:-}" \
        -- "$NG" "$@" ) >"$_out_tmp" 2>"$_err_tmp"
    _rc=$?
    _stdout=$(<"$_out_tmp"); _stderr=$(<"$_err_tmp")
    rm -f "$_out_tmp" "$_err_tmp"
    printf -v "$_out_var" '%s' "$_stdout"
    printf -v "$_err_var" '%s' "$_stderr"
    printf -v "$_rc_var"  '%s' "$_rc"
}

# ---- Test 1: --dry-run renders delimiters + headline + labels ----------

echo '=== ng nexus-identity --dry-run → block with delimiters, headline, labels ==='
run_ng out err rc nexus-identity --dry-run
assert_eq        "exit 0"                            "$rc" "0"
assert_contains  "start delimiter"                   "$out" "<!-- nexus-identity:start -->"
assert_contains  "end delimiter"                     "$out" "<!-- nexus-identity:end -->"
assert_contains  "working-directory headline"        "$out" "**Working directory:**"
assert_contains  "Host label"                        "$out" "| Host |"
assert_contains  "asset+issue repo label"            "$out" "Asset + issue repo"
assert_contains  "implementation-clone label"        "$out" "Implementation clone"
assert_contains  "watcher pidfile label"             "$out" "Watcher pidfile"
assert_contains  "watcher log label"                 "$out" "Watcher log"
assert_contains  "auto-generated do-not-edit note"   "$out" "auto-generated by"

# ---- Test 2: fields DERIVED from NEXUS_ROOT + config repo --------------

echo '=== identity block reflects NEXUS_ROOT + config repo (nothing hardcoded) ==='
assert_contains  "working dir = fixture NEXUS_ROOT"  "$out" "$FAKE_NEXUS"
assert_contains  "repo from config stub"             "$out" "your-org/example-nexus"
assert_contains  "watcher pidfile derived from root" "$out" "$FAKE_NEXUS/monitor/.state/watcher.pid"

# ---- Test 3: implementation-clone row degrades without a git checkout --

echo '=== identity block degrades gracefully when root is not a git checkout ==='
assert_contains  "no-git-origin fallback"            "$out" "(no git origin)"

# ---- Test 4: --dry-run is idempotent (the anti-drift point) -----------

echo '=== ng nexus-identity --dry-run is idempotent (two runs identical) ==='
run_ng out_a err_a rc_a nexus-identity --dry-run
run_ng out_b err_b rc_b nexus-identity --dry-run
assert_eq        "two dry-runs identical"            "$out_a" "$out_b"

# ---- Test 5: --dry-run does NOT touch GitHub --------------------------

echo '=== ng nexus-identity --dry-run issues no GitHub write ==='
run_ng out err rc nexus-identity --dry-run
calls=$(<"$CAPTURE")
assert_not_contains "no PATCH on dry-run"            "$calls" "-X PATCH"

# ---- Test 6: --upsert-overview PATCHes the block into the issue body ---

echo '=== ng nexus-identity --upsert-overview → PATCH carrying the identity block ==='
run_ng out err rc nexus-identity --upsert-overview
assert_eq        "exit 0"                            "$rc" "0"
calls=$(<"$CAPTURE")
assert_contains  "PATCH issued"                      "$calls" "-X PATCH"
patched=$(<"$BODY_CAPTURE")
assert_contains  "patched body has start delimiter"  "$patched" "nexus-identity:start"
assert_contains  "patched body has end delimiter"    "$patched" "nexus-identity:end"
assert_contains  "patched body preserves prose"      "$patched" "body prose"

# ---- Test 7: upsert REPLACES an existing block (no duplication) --------

echo '=== ng nexus-identity --upsert-overview replaces an existing block in place ==='
seeded="$WORK/seeded-body.md"
printf '## Nexus overview\n\n<!-- nexus-identity:start -->\nSTALE IDENTITY\n<!-- nexus-identity:end -->\n\ntrailing prose\n' > "$seeded"
MOCK_BODY_FILE="$seeded" run_ng out err rc nexus-identity --upsert-overview
assert_eq        "exit 0"                            "$rc" "0"
patched=$(<"$BODY_CAPTURE")
assert_not_contains "stale block removed"            "$patched" "STALE IDENTITY"
assert_contains     "trailing prose preserved"       "$patched" "trailing prose"
# Exactly one start delimiter survives (no duplicate block).
ndelim=$(grep -c 'nexus-identity:start' <<<"$patched")
assert_eq        "exactly one identity block"        "$ndelim" "1"

# ---- summary ------------------------------------------------------------

th_summary_and_exit
